In [1]:
pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (1.5.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.9/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# FDCL18

In [3]:
import pandas as pd

In [64]:
data = pd.read_csv('/content/drive/My Drive/hatespeech_text_label_vote_RESTRICTED_100K.csv')

In [65]:
category_counts = data['Label'].value_counts()

In [66]:
print("Category counts in FDCL18 dataset:")
print(category_counts)

Category counts in FDCL18 dataset:
normal     53851
abusive    27150
spam       14029
hateful     4965
Name: Label, dtype: int64

In [7]:
import numpy as np

In [67]:
aae_data = pd.read_csv('/content/drive/My Drive/fdcl18_aae.csv', header=None, sep=',|\s+', engine='python', usecols=[0])# Use header=None and set the separator to tab

In [68]:
aae_data.rename(columns={0: 'AAE_prob'}, inplace=True)

In [69]:
# Concatenate the first column(AAE_prob) from aae_data to the last column of data
result = pd.concat([data, aae_data['AAE_prob']], axis=1)

In [70]:
result

,Tweet text,Label,Votes for the majority label,AAE_prob
0,RT @Papapishu: Man it would fucking rule if we...,abusive,4,0.192171
1,It is time to draw close to Him &#128591;&#127...,normal,4,0.136180
2,if you notice me start to act different or dis...,normal,5,0.424316
3,"Forget unfollowers, I believe in growing. 7 ne...",normal,3,0.119572
4,RT @Vitiligoprince: Hate Being sexually Frustr...,abusive,4,0.532083
...,...,...,...,...
99990,RT @shangros: my fucking queen https://t.co/wa...,abusive,5,0.252232
99991,#Osteporosis treated with #PEMF - rebuild bone...,normal,3,0.302541
99992,@LGUSAMobile why does my phone screen keeps fl...,normal,3,0.188668
99993,#bigdata vs. #reality ... but equally applies ...,normal,5,0.116557
99994,"you can do whatever you choose, if you first g...",normal,5,0.087409

In [71]:
from scipy.stats import pearsonr
from nltk.tokenize import TweetTokenizer

In [72]:
#result1= result.head(170)
result['AAE_prob'].fillna(0, inplace=True)

In [77]:
labels = ['normal', 'abusive', 'hateful', 'spam']
correlations = {}

for label in labels:
    # Create a binary column indicating the presence of the current label
    result[f'{label}_binary'] = np.where(result['Label'] == label, 1, 0)
    
    # Calculate the correlation between AAE probability and the binary column for the current label
    corr, _ = pearsonr(result['AAE_prob'], result[f'{label}_binary'])
    correlations[label] = corr

# Print the AAE correlations
print("AAE correlations for each label in the dataset:")
for label, corr in correlations.items():
    print(f"{label}: {corr:.3f}")

AAE correlations for each label in the dataset:
normal: -0.305
abusive: 0.345
hateful: 0.136
spam: -0.089

# DWMW17

In [44]:
# Used DWMW17 from https://github.com/t-davidson/hate-speech-and-offensive-language/tree/master/data
data_path = 'https://raw.githubusercontent.com/t-davidson/hate-speech-and-offensive-language/master/data/labeled_data.csv'
DWMW17data = pd.read_csv(data_path)

In [45]:
DWMW17data

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an..."
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [51]:
# Get the counts for each class
class_counts = DWMW17data['class'].value_counts()
print(class_counts)

offensive      19190
none            4163
hate speech     1430
Name: class, dtype: int64

In [52]:
aae_data17 = pd.read_csv('/content/drive/My Drive/aae.txt', header=None, sep=',|\s+', engine='python', usecols=[0])# Use header=None and set the separator to tab

In [54]:
aae_data17.rename(columns={0: 'AAE_prob'}, inplace=True)

In [55]:
aae_data17

       AAE_prob
0      0.241682
1      0.827913
2      0.415841
3      0.458594
4      0.563099
...         ...
24778  0.554410
24779  0.271660
24780  0.811923
24781  0.796043
24782  0.085754

[24783 rows x 1 columns]

In [56]:
# Concatenate the first column(AAE_prob) from aae_data to the last column of data
result17 = pd.concat([DWMW17data, aae_data17['AAE_prob']], axis=1)

In [57]:
result17

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet,AAE_prob
0,0,3,0,0,3,none,!!! RT @mayasolovely: As a woman you shouldn't...,0.241682
1,1,3,0,3,0,offensive,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,0.827913
2,2,3,0,3,0,offensive,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,0.415841
3,3,3,0,2,1,offensive,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,0.458594
4,4,6,0,6,0,offensive,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,0.563099
...,...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,offensive,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,0.554410
24779,25292,3,0,1,2,none,"you've gone and broke the wrong heart baby, an...",0.271660
24780,25294,3,0,3,0,offensive,young buck wanna eat!!.. dat nigguh like I ain...,0.811923
24781,25295,6,0,6,0,offensive,youu got wild bitches tellin you lies,0.796043
24782,25296,3,0,0,3,none,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,0.085754

In [59]:
from scipy.stats import pearsonr
result17['AAE_prob'].fillna(0, inplace=True)

##calculates the Pearson correlation coefficient between "AAE_prob" and each label in the list of labels.
## The results are stored in a dictionary called "correlations", where the keys are the labels and the values are the correlation coefficients.
labels = ['hate_speech', 'offensive_language', 'neither']
correlations = {label: pearsonr(result17['AAE_prob'], result17[label])[0] for label in labels}

print("AAE correlations for each category in the dataset:")
for label, corr in correlations.items():
    print(f"{label}: {corr:.3f}")

AAE correlations for each category in the dataset:
hate_speech: -0.044
offensive_language: 0.366
neither: -0.378